Add `@ballocs` macro for getting number of allocations
JuliaCI/BenchmarkTools.jl pull request #292
Opened 2022-10-28 16:18 UTC by nickrobinson251

- partner to https://github.com/JuliaLang/julia/pull/47367
- opened as draft til the Julia one is settled and we can match the name from there
- with apologies for the name that currently results from following the "add a `b` prefix" naming convention here

2022-11-24 12:25 UTC, nickrobinson251 commented
bump :) is someone available to review this please?

2022-12-01 13:55 UTC, KristofferC commented
I don't really understand the purpose of this macro and the `@ballocated` one. Why would you run a function potentially thousands of times (until the execution time is within some noise level) to count the number of allocations (which is not noisy). Isn't one for compiling the function and one for counting the allocations enough?

2022-12-01 17:56 UTC, nickrobinson251 commented
i hope to use it the same way `@ballocated` is already used in e.g. the NamedDims tests: https://github.com/invenia/NamedDims.jl/search?q=ballocated

running these functions many times is no issue (since they're written to be basically no cost), but it's a lot nicer (i.e. less burden on the package developers writing the tests) to use `@ballocated` rather than having to makes sure things have already compiled and then using `@allocated`

2023-06-12 22:02 UTC, gdalle commented
> but i think setting default evals/samples could make sense -- should i make that change?

Sounds like a good idea to me, although it will have to be thoroughly documented for users not to be surprised.

2023-09-18 17:44 UTC, gdalle commented on src/execution.jl
> +Similar to the `@allocs` macro included with Julia (v1.9+),
```suggestion
Similar to the `@allocations` macro included with Julia (v1.9+),
```

2023-09-18 17:46 UTC, gdalle requested changes

2023-09-18 17:46 UTC, gdalle commented on src/execution.jl
> +Similar to the `@allocs` macro included with Julia (v1.9+),
```suggestion
Similar to the `@allocations` macro included with Julia (v1.9+),
```

2023-09-18 17:46 UTC, gdalle commented on src/execution.jl
> +
Can we set a default value `evals=1 samples=2` for this one? And explain it in the docstring?

2023-09-18 18:39 UTC, gdalle commented on src/execution.jl
> +
Then again it would be incoherent with the other `@bstuff` macros so I'm torn

2025-02-05 10:12 UTC, nickrobinson251 commented
superseded by https://github.com/JuliaCI/BenchmarkTools.jl/pull/383

2025-02-05 10:12 UTC, closed without merging